server:
  port: 8081
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, refresh, shutdown

service:
  host: localhost
  port: 5454
  bot:
    name: AlbertGafarovBetBot
    token: 6521471388:AAGP25xpwPlMzoExAe_XTrUtweUl9U2cgUk
grpc:
  server:
    port: 5455