logging:
  level:
    org.hibernate.type.descriptor.sql: warn
    ru.gafarov.betservice.service.impl.BetServiceImpl: debug
    ru.gafarov.betservice.service.impl.FriendServiceImpl: debug
    ru.gafarov.betservice.transformer.impl.BetTransformerImpl: debug
server:
  port: 8080
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, refresh, shutdown

service:
  host: localhost
  port: 5455
  logging:
    - BetService

hibernate:
  use_sql_comments: 'true'
  format_sql: 'true'
  show_sql: 'true'
spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/ag3d
    change-log: classpath:liquibase/db.changelog-master.xml
    default-schema: betbot
    password: 'bet_admin'
    user: bet_admin
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bet_user
    password: 'bet_user'
    url: jdbc:postgresql://localhost:5432/ag3d?currentSchema=betbot

  jpa:
    show-sql: 'false'
    properties:
      hibernate:
        format_sql: 'true'
        default_schema: betbot

database:
  schema: betbot

grpc:
  server:
    port: 5454