hibernate:
  use_sql_comments: 'true'
  format_sql: 'true'
  show_sql: 'true'
spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/AG3D
    change-log: classpath:liquibase/db.changelog-master.xml
    default-schema: betbot
    password: '123'
    user: postgres
  datasource:
    password: '123456'
    driver-class-name: org.postgresql.Driver
    username: messenger
    url: jdbc:postgresql://localhost:5432/AG3D?currentSchema=betbot

  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        default_schema: betbot

database:
  schema: betbot
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
grpc:
  server:
    port: 5454
